name: Build frontend

on:
  push

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
